rearranged Benchmark/G2

diff --git a/src/Benchmarks/G2/src/g2_analyse b/src/Benchmarks/G2/src/g2_analyse
--- a/src/Benchmarks/G2/src/g2_analyse
+++ b/src/Benchmarks/G2/src/g2_analyse
@@ -9,28 +9,34 @@
 #=================================================================
 THISDIR=$(pwd)
 G1DIR=$THISDIR
+SAMPLEDIR=$G1DIR/src/Strcfiles # directory holding the structure files
+STPDIR=$G1DIR/src/Speciesfiles # define directory with species information
+CASESDIR=$G1DIR/Cases
+BINDIR=$G1DIR/bin
 #
-#== define directory holding the structure files
-SAMPLEDIR=$G1DIR/bin/Strcfiles
+####################################################################
+####################################################################
 if [[ ! -d $SAMPLEDIR ]]; then 
    echo "error in $0: SAMPLEDIR does not exist"
    exit 1 
 fi
-#== define directory with species information
-STPDIR=$G1DIR/bin/Speciesfiles
 if [[ ! -d $STPDIR ]]; then 
    echo "error in $0: STPDIR does not exist"
    exit 1 
 fi
-CASESDIR=$G1DIR/Cases
 #
 #####################################################################
 ##       compile g2_analyse.f90
 #####################################################################
-echo "compiling g2_analyse.f90 ..."
-gfortran -g -o g2_analyse.x ${G1DIR}/bin/g2_analyse.f90
-RC=$?
-if [[ $RC != 0 ]] ; then echo "error in $0: compilation failed"; exit 1 ; fi
+if [[ ! -d $BINDIR ]]; then mkdir $BINDIR ; fi
+if [[ ${G1DIR}/src/g2_analyse.f90 -nt ${BINDIR}/g2_analyse.x ]] ; then
+  cd $BINDIR
+  echo "compiling g2_analyse.f90 ..."
+  gfortran -g -o g2_analyse.x ${G1DIR}/src/g2_analyse.f90
+  RC=$?
+  if [[ $RC != 0 ]] ; then echo "error in $0: compilation failed"; exit 1 ; fi
+  cd $THISDIR
+fi
 #
 #####################################################################
 ## update readpaw.in
@@ -39,14 +45,16 @@ echo "building readpaw.in ..."
 if [[ -f readpaw.in ]] ; then rm readpaw.in ; fi
 for FILE in ${SAMPLEDIR}/*.strc_sample ; do
   NAME=${FILE%.strc_sample} # strip extension
-  NAME=${NAME##*/}     #  remove all preceeding directories
+  NAME=${NAME##*/}          # strip preceeding directories
   DIR=$CASESDIR/$NAME
-  if  ! test -s $DIR ; then
-    echo 'system $NAME does not exist; exit'
+  if [[  ! -s $DIR ]] ; then
+    echo "system $NAME does not exist"
   fi
   X=$(paw_get -n -w etot ${DIR}/$NAME)
   if [[ ! $X  = error* ]] ; then
     echo "  '$NAME' $X " >>${G1DIR}/readpaw.in
+  else
+    echo "system $NAME produced an error"
   fi
 done
 #
@@ -54,6 +62,6 @@ done
 ##  run analysis
 #####################################################################
 echo "building readpaw.out ..."
-g2_analyse.x <readpaw.in >readpaw.out
+${BINDIR}/g2_analyse.x <readpaw.in >readpaw.out
 echo " ...done"
 exit 0
diff --git a/src/Benchmarks/G2/src/g2_makedo b/src/Benchmarks/G2/src/g2_makedo
--- a/src/Benchmarks/G2/src/g2_makedo
+++ b/src/Benchmarks/G2/src/g2_makedo
@@ -32,21 +32,20 @@ THISDIR=$(pwd)
 if [[ $V = yes ]] ; then echo THISDIR=$THISDIR ; fi
 G1DIR=$THISDIR
 #
-#== define directory holding the structure files
-SAMPLEDIR=$G1DIR/bin/Strcfiles
-if [[ ! -d $SAMPLEDIR ]]; then 
-   echo "error in $0: SAMPLEDIR does not exist"
-   exit 1 
-fi
-#== define directory with species information
-STPDIR=$G1DIR/bin/Speciesfiles
+SAMPLEDIR=$G1DIR/src/Strcfiles # directory holding the structure files
+STPDIR=$G1DIR/src/Speciesfiles # directory with species information
+CASESDIR=$G1DIR/Cases
+DOSCRIPT=$G1DIR/g2_do_sample
+#
 if [[ ! -d $STPDIR ]]; then 
    echo "error in $0: STPDIR does not exist"
    exit 1 
 fi
+if [[ ! -d $SAMPLEDIR ]]; then 
+   echo "error in $0: SAMPLEDIR does not exist"
+   exit 1 
+fi
 #
-CASESDIR=$G1DIR/Cases
-DOSCRIPT=$G1DIR/g2_do_sample
 #######################################################################
 #  prepare calcall_sample
 #######################################################################
@@ -74,15 +73,14 @@ echo '}'                                          >>$DOSCRIPT
 # Produce a shell script calcall_sample to be executed
 ################################################################
 echo "LIST=\"\""                                 >>$DOSCRIPT
+if [[ ! -d $CASESDIR ]] ; then mkdir $CASESDIR ; fi
 for FILE in $SAMPLEDIR/*.strc_sample ; do
   if [[ $V = yes ]] ; then echo FILE=$FILE ; fi
 
   NAME=${FILE%.strc_sample} # strip extension
   NAME=${NAME##*/}     #  remove all preceeding directories
   DIR=$CASESDIR/$NAME
-  if [[ ! -d $DIR ]] ; then
-    mkdir $DIR
-  fi
+  if [[ ! -d $DIR ]] ; then mkdir $DIR; fi
   paw_resolve -r"LATTICE=0.0 8.5 8.5 8.5 0.0 8.5 8.5 8.5 0.0" \
               -fHYDROGEN=$STPDIR/h.species \
               -fLITHIUM=$STPDIR/li.species \
@@ -103,7 +101,6 @@ for FILE in $SAMPLEDIR/*.strc_sample ; do
   #   create sample control file
     ROOT=${DIR}/$NAME
     ROOT=${ROOT#$G1DIR/} 
-#    echo 'calcone' ${ROOT} >>$DOSCRIPT
     echo "LIST=\"\$LIST ${ROOT}\"" >>$DOSCRIPT
 done
 echo "for X in \$LIST; do"         >>$DOSCRIPT
@@ -113,8 +110,3 @@ echo "done"                        >>$DOSCRIPT
 echo 'exit 0'                      >>$DOSCRIPT
 chmod +x $DOSCRIPT
 exit 0
-
-
-
-
-
