bugfix in f90pp.in and in paw_waves1.f90 (does not affect results)

diff --git a/src/Buildtools/F90PP/f90pp.in b/src/Buildtools/F90PP/f90pp.in
--- a/src/Buildtools/F90PP/f90pp.in
+++ b/src/Buildtools/F90PP/f90pp.in
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 set +x
 ########################################################################
 ###                                                                   ##
@@ -142,9 +142,9 @@ fi
 ${DO1} < $ARG | $DO2 | $DO3 | $DO4 
 RC=$?
 if [[ $RC != 0 ]] ; then 
-  echo "error in $0: last command failed with RC=$RC"
-  echo "try to  execute ulimit -s unlimited"
-  exit 1
+  echo "error in $0: last command failed with RC=$RC" 
+  echo "try to  execute ulimit -s unlimited" 
+  exit 2
 fi              
 exit 0
 
